# Generated by Django 5.0.7 on 2024-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Product Name')),
                ('pdetail', models.CharField(max_length=100)),
                ('cat', models.IntegerField(choices=[(1, 'Mobile'), (2, 'Shoese'), (3, 'Cloth')], verbose_name='Category')),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
